"""
Candidate data loader — rich synthetic dataset of 20 diverse engineering candidates.
In production, replace with your ATS/database connector.
"""


def load_candidates() -> list[dict]:
    return [
        {
            "id": "c001",
            "name": "Aisha Patel",
            "current_title": "Senior ML Engineer",
            "years_of_experience": 7,
            "education": "M.S. Computer Science, Stanford University",
            "skills": ["Python", "PyTorch", "TensorFlow", "MLflow", "Kubernetes", "Spark", "SQL", "Docker"],
            "domain_experience": ["recommendation systems", "NLP", "computer vision"],
            "past_roles": [
                {"title": "ML Engineer", "company": "Netflix", "years": 3},
                {"title": "Data Scientist", "company": "Airbnb", "years": 2},
                {"title": "Research Intern", "company": "Google Brain", "years": 1},
            ],
            "github": {"repos": 42, "stars": 1200, "contributions_last_year": 680, "has_popular_project": True},
            "publications": ["NeurIPS 2022: Efficient Transformers for RecSys"],
            "open_source_contributor": True,
            "endorsements": 38,
            "num_jobs": 3,
        },
        {
            "id": "c002",
            "name": "Marcus Webb",
            "current_title": "Staff Backend Engineer",
            "years_of_experience": 10,
            "education": "B.S. Computer Engineering, MIT",
            "skills": ["Go", "Rust", "PostgreSQL", "Redis", "Kubernetes", "gRPC", "Kafka", "Terraform"],
            "domain_experience": ["distributed systems", "high-throughput APIs", "platform engineering"],
            "past_roles": [
                {"title": "Staff Engineer", "company": "Stripe", "years": 4},
                {"title": "Senior Engineer", "company": "Dropbox", "years": 3},
                {"title": "Engineer", "company": "LinkedIn", "years": 2},
            ],
            "github": {"repos": 28, "stars": 3400, "contributions_last_year": 420, "has_popular_project": True},
            "publications": [],
            "open_source_contributor": True,
            "endorsements": 55,
            "num_jobs": 3,
        },
        {
            "id": "c003",
            "name": "Sofia Reyes",
            "current_title": "Frontend Lead",
            "years_of_experience": 8,
            "education": "B.S. Computer Science, UT Austin",
            "skills": ["React", "TypeScript", "Next.js", "GraphQL", "Webpack", "CSS-in-JS", "Testing Library", "Storybook"],
            "domain_experience": ["micro-frontends", "design systems", "performance optimization"],
            "past_roles": [
                {"title": "Frontend Lead", "company": "Figma", "years": 3},
                {"title": "Senior Frontend Engineer", "company": "Shopify", "years": 3},
                {"title": "UI Engineer", "company": "Twilio", "years": 1},
            ],
            "github": {"repos": 35, "stars": 890, "contributions_last_year": 510, "has_popular_project": True},
            "publications": [],
            "open_source_contributor": True,
            "endorsements": 44,
            "num_jobs": 3,
        },
        {
            "id": "c004",
            "name": "Devon Kim",
            "current_title": "ML Engineer",
            "years_of_experience": 4,
            "education": "B.S. Statistics, UC Berkeley",
            "skills": ["Python", "scikit-learn", "TensorFlow", "SQL", "Airflow", "Docker"],
            "domain_experience": ["fraud detection", "tabular ML", "data pipelines"],
            "past_roles": [
                {"title": "ML Engineer", "company": "Square", "years": 2},
                {"title": "Data Analyst", "company": "Lyft", "years": 1},
            ],
            "github": {"repos": 18, "stars": 120, "contributions_last_year": 200, "has_popular_project": False},
            "publications": [],
            "open_source_contributor": False,
            "endorsements": 15,
            "num_jobs": 2,
        },
        {
            "id": "c005",
            "name": "James O'Brien",
            "current_title": "Principal Engineer",
            "years_of_experience": 15,
            "education": "Ph.D. Computer Science, Carnegie Mellon",
            "skills": ["Python", "C++", "Rust", "distributed systems", "ML infrastructure", "CUDA", "Spark", "Flink"],
            "domain_experience": ["ML systems", "search", "large-scale data processing"],
            "past_roles": [
                {"title": "Principal Engineer", "company": "Meta AI", "years": 5},
                {"title": "Staff Engineer", "company": "Twitter", "years": 4},
                {"title": "Research Scientist", "company": "Microsoft Research", "years": 4},
            ],
            "github": {"repos": 60, "stars": 7800, "contributions_last_year": 290, "has_popular_project": True},
            "publications": ["ICML 2019", "OSDI 2021", "SOSP 2023"],
            "open_source_contributor": True,
            "endorsements": 90,
            "num_jobs": 3,
        },
        {
            "id": "c006",
            "name": "Priya Nair",
            "current_title": "Senior Frontend Engineer",
            "years_of_experience": 6,
            "education": "B.Tech CSE, IIT Bombay",
            "skills": ["React", "TypeScript", "Vue.js", "Node.js", "GraphQL", "Webpack", "Jest"],
            "domain_experience": ["e-commerce", "dashboards", "real-time UIs"],
            "past_roles": [
                {"title": "Senior Frontend Engineer", "company": "Razorpay", "years": 3},
                {"title": "Frontend Engineer", "company": "Zomato", "years": 2},
            ],
            "github": {"repos": 22, "stars": 340, "contributions_last_year": 380, "has_popular_project": False},
            "publications": [],
            "open_source_contributor": True,
            "endorsements": 28,
            "num_jobs": 2,
        },
        {
            "id": "c007",
            "name": "Liam Foster",
            "current_title": "Backend Engineer",
            "years_of_experience": 3,
            "education": "B.S. Software Engineering, Georgia Tech",
            "skills": ["Python", "Django", "PostgreSQL", "Redis", "Docker", "AWS"],
            "domain_experience": ["REST APIs", "SaaS", "authentication"],
            "past_roles": [
                {"title": "Backend Engineer", "company": "HubSpot", "years": 2},
                {"title": "Junior Engineer", "company": "Startup XYZ", "years": 1},
            ],
            "github": {"repos": 14, "stars": 55, "contributions_last_year": 150, "has_popular_project": False},
            "publications": [],
            "open_source_contributor": False,
            "endorsements": 8,
            "num_jobs": 2,
        },
        {
            "id": "c008",
            "name": "Yuki Tanaka",
            "current_title": "Research Engineer",
            "years_of_experience": 5,
            "education": "M.S. AI, University of Tokyo",
            "skills": ["Python", "PyTorch", "JAX", "CUDA", "Triton", "MLflow", "Weights & Biases"],
            "domain_experience": ["LLM training", "RLHF", "efficient inference"],
            "past_roles": [
                {"title": "Research Engineer", "company": "Cohere", "years": 2},
                {"title": "ML Researcher", "company": "RIKEN", "years": 2},
            ],
            "github": {"repos": 30, "stars": 2100, "contributions_last_year": 720, "has_popular_project": True},
            "publications": ["ACL 2023", "EMNLP 2022"],
            "open_source_contributor": True,
            "endorsements": 32,
            "num_jobs": 2,
        },
        {
            "id": "c009",
            "name": "Carmen Valdez",
            "current_title": "Senior Data Engineer",
            "years_of_experience": 7,
            "education": "M.S. Data Science, Columbia University",
            "skills": ["Python", "Spark", "dbt", "Airflow", "Snowflake", "Kafka", "SQL", "Terraform"],
            "domain_experience": ["data lakehouse", "ETL pipelines", "streaming analytics"],
            "past_roles": [
                {"title": "Senior Data Engineer", "company": "Databricks", "years": 3},
                {"title": "Data Engineer", "company": "Palantir", "years": 3},
            ],
            "github": {"repos": 20, "stars": 180, "contributions_last_year": 260, "has_popular_project": False},
            "publications": [],
            "open_source_contributor": True,
            "endorsements": 22,
            "num_jobs": 2,
        },
        {
            "id": "c010",
            "name": "Ethan Brooks",
            "current_title": "Full Stack Engineer",
            "years_of_experience": 5,
            "education": "B.S. Computer Science, University of Michigan",
            "skills": ["React", "Node.js", "TypeScript", "Python", "PostgreSQL", "GraphQL", "AWS"],
            "domain_experience": ["SaaS products", "B2B dashboards", "API design"],
            "past_roles": [
                {"title": "Full Stack Engineer", "company": "Notion", "years": 3},
                {"title": "Software Engineer", "company": "Webflow", "years": 1},
            ],
            "github": {"repos": 25, "stars": 410, "contributions_last_year": 300, "has_popular_project": False},
            "publications": [],
            "open_source_contributor": True,
            "endorsements": 18,
            "num_jobs": 2,
        },
        {
            "id": "c011",
            "name": "Fatima Al-Hassan",
            "current_title": "MLOps Engineer",
            "years_of_experience": 6,
            "education": "M.Eng. Systems Engineering, Cairo University",
            "skills": ["Python", "Kubeflow", "MLflow", "Kubernetes", "Helm", "Prometheus", "Terraform", "FastAPI"],
            "domain_experience": ["ML platform", "model deployment", "CI/CD for ML"],
            "past_roles": [
                {"title": "MLOps Engineer", "company": "Booking.com", "years": 3},
                {"title": "DevOps Engineer", "company": "Careem", "years": 2},
            ],
            "github": {"repos": 32, "stars": 560, "contributions_last_year": 440, "has_popular_project": True},
            "publications": [],
            "open_source_contributor": True,
            "endorsements": 26,
            "num_jobs": 2,
        },
        {
            "id": "c012",
            "name": "Noah Jensen",
            "current_title": "iOS Engineer",
            "years_of_experience": 6,
            "education": "B.S. CS, University of Copenhagen",
            "skills": ["Swift", "SwiftUI", "Objective-C", "XCTest", "CoreData", "UIKit"],
            "domain_experience": ["mobile apps", "consumer products", "health tech"],
            "past_roles": [
                {"title": "Senior iOS Engineer", "company": "Spotify", "years": 3},
                {"title": "iOS Developer", "company": "Simplementation", "years": 2},
            ],
            "github": {"repos": 16, "stars": 290, "contributions_last_year": 180, "has_popular_project": False},
            "publications": [],
            "open_source_contributor": False,
            "endorsements": 20,
            "num_jobs": 2,
        },
        {
            "id": "c013",
            "name": "Riya Mehta",
            "current_title": "Applied Scientist",
            "years_of_experience": 5,
            "education": "Ph.D. ML, ETH Zurich",
            "skills": ["Python", "PyTorch", "TensorFlow", "R", "Spark", "SQL", "A/B testing", "causal inference"],
            "domain_experience": ["RecSys", "growth", "experimentation platforms"],
            "past_roles": [
                {"title": "Applied Scientist", "company": "Pinterest", "years": 3},
                {"title": "Research Intern", "company": "DeepMind", "years": 1},
            ],
            "github": {"repos": 24, "stars": 870, "contributions_last_year": 490, "has_popular_project": True},
            "publications": ["RecSys 2022", "WWW 2023"],
            "open_source_contributor": True,
            "endorsements": 34,
            "num_jobs": 2,
        },
        {
            "id": "c014",
            "name": "Samuel Okafor",
            "current_title": "Security Engineer",
            "years_of_experience": 8,
            "education": "B.S. CS, University of Lagos",
            "skills": ["Python", "Go", "Rust", "cryptography", "zero-trust", "SIEM", "penetration testing"],
            "domain_experience": ["AppSec", "infrastructure security", "compliance"],
            "past_roles": [
                {"title": "Security Engineer", "company": "Cloudflare", "years": 4},
                {"title": "Security Analyst", "company": "Access Bank", "years": 3},
            ],
            "github": {"repos": 19, "stars": 440, "contributions_last_year": 210, "has_popular_project": False},
            "publications": [],
            "open_source_contributor": True,
            "endorsements": 29,
            "num_jobs": 2,
        },
        {
            "id": "c015",
            "name": "Chloe Martin",
            "current_title": "Data Scientist",
            "years_of_experience": 3,
            "education": "M.S. Statistics, University of Edinburgh",
            "skills": ["Python", "R", "scikit-learn", "SQL", "Tableau", "Statsmodels"],
            "domain_experience": ["forecasting", "A/B testing", "marketing analytics"],
            "past_roles": [
                {"title": "Data Scientist", "company": "Deliveroo", "years": 2},
            ],
            "github": {"repos": 10, "stars": 40, "contributions_last_year": 90, "has_popular_project": False},
            "publications": [],
            "open_source_contributor": False,
            "endorsements": 10,
            "num_jobs": 1,
        },
        {
            "id": "c016",
            "name": "Arjun Sharma",
            "current_title": "Senior Backend Engineer",
            "years_of_experience": 7,
            "education": "B.Tech CS, IIT Delhi",
            "skills": ["Java", "Spring Boot", "Kotlin", "Kafka", "PostgreSQL", "Redis", "gRPC", "Docker"],
            "domain_experience": ["fintech", "payments", "high-reliability systems"],
            "past_roles": [
                {"title": "Senior Engineer", "company": "PhonePe", "years": 3},
                {"title": "Software Engineer", "company": "Flipkart", "years": 3},
            ],
            "github": {"repos": 21, "stars": 310, "contributions_last_year": 330, "has_popular_project": False},
            "publications": [],
            "open_source_contributor": True,
            "endorsements": 31,
            "num_jobs": 2,
        },
        {
            "id": "c017",
            "name": "Luna Fischer",
            "current_title": "Platform Engineer",
            "years_of_experience": 6,
            "education": "M.S. CS, TU Munich",
            "skills": ["Go", "Kubernetes", "Helm", "Prometheus", "Terraform", "AWS", "gRPC", "Rust"],
            "domain_experience": ["developer platforms", "observability", "infrastructure"],
            "past_roles": [
                {"title": "Platform Engineer", "company": "N26", "years": 3},
                {"title": "DevOps Engineer", "company": "SAP", "years": 2},
            ],
            "github": {"repos": 36, "stars": 1100, "contributions_last_year": 560, "has_popular_project": True},
            "publications": [],
            "open_source_contributor": True,
            "endorsements": 33,
            "num_jobs": 2,
        },
        {
            "id": "c018",
            "name": "Tomás Rivera",
            "current_title": "ML Engineer",
            "years_of_experience": 5,
            "education": "M.S. AI, Universidad de los Andes",
            "skills": ["Python", "PyTorch", "Ray", "MLflow", "FastAPI", "Docker", "PostgreSQL"],
            "domain_experience": ["NLP", "real-time inference", "model optimization"],
            "past_roles": [
                {"title": "ML Engineer", "company": "Rappi", "years": 2},
                {"title": "ML Research Intern", "company": "NVIDIA", "years": 1},
            ],
            "github": {"repos": 26, "stars": 650, "contributions_last_year": 410, "has_popular_project": True},
            "publications": ["LatinX in AI NeurIPS Workshop 2022"],
            "open_source_contributor": True,
            "endorsements": 21,
            "num_jobs": 2,
        },
        {
            "id": "c019",
            "name": "Grace Osei",
            "current_title": "Engineering Manager",
            "years_of_experience": 12,
            "education": "B.S. CS, Kwame Nkrumah University",
            "skills": ["Python", "Go", "system design", "team leadership", "OKRs", "incident management"],
            "domain_experience": ["engineering leadership", "platform teams", "0-to-1 products"],
            "past_roles": [
                {"title": "Engineering Manager", "company": "Flutterwave", "years": 4},
                {"title": "Staff Engineer", "company": "Andela", "years": 4},
                {"title": "Software Engineer", "company": "IBM", "years": 3},
            ],
            "github": {"repos": 12, "stars": 140, "contributions_last_year": 80, "has_popular_project": False},
            "publications": [],
            "open_source_contributor": False,
            "endorsements": 62,
            "num_jobs": 3,
        },
        {
            "id": "c020",
            "name": "Wei Zhang",
            "current_title": "Staff ML Engineer",
            "years_of_experience": 9,
            "education": "Ph.D. Statistics, Tsinghua University",
            "skills": ["Python", "PyTorch", "TensorFlow", "Kubeflow", "Spark", "Scala", "CUDA", "MLflow"],
            "domain_experience": ["RecSys", "ML platform", "feature stores", "online learning"],
            "past_roles": [
                {"title": "Staff ML Engineer", "company": "ByteDance", "years": 4},
                {"title": "ML Engineer", "company": "JD.com", "years": 3},
            ],
            "github": {"repos": 38, "stars": 2600, "contributions_last_year": 500, "has_popular_project": True},
            "publications": ["KDD 2020", "RecSys 2021", "SIGIR 2022"],
            "open_source_contributor": True,
            "endorsements": 58,
            "num_jobs": 2,
        },
    ]
